### ISSUE TITLE
SIGSEGV fatal signal - Snort 3.1.0.0  - no solution

### ISSUE THREAD

**Issue by WingerHusar** [snort3/snort3#163]
Hi all,

I have problem with snort when it is running. After some time it crashes. Sometimes after 5 min, sometimes 20 min.

I saw previous issues but I have something else in logs.  I followed instruction for Ubuntu 18/20. I installed all functions.

Command:  /usr/local/bin/snort -c /usr/local/etc/snort/snort.lua -s 65535 -k none -l /var/log/snort -D -i eno4 -m 0x1b --create-pidfile --plugin-path=/usr/local/lib/snort_extra

Hyperscan is installed.
<pre>
Snort (PID 117930) caught fatal signal: SIGSEGV (11)
Version: 3.1.0.0
Backtrace:
#0 0x5562f7954f8b in _ZN16TcpStreamTracker20finalize_held_packetEPN5snort6PacketE+0xb (/usr/local/bin/snort @0x5562f7675000)
#1 0x5562f794a742 in _ZN14TcpReassembler12flush_to_seqER19TcpReassemblerStatejPN5snort6PacketEj+0xe2 (/usr/local/bin/snort @0x5562f7675000)
#2 0x5562f794ac1e in _ZN14TcpReassembler11final_flushER19TcpReassemblerStatePN5snort6PacketEj+0x2e (/usr/local/bin/snort @0x5562f7675000)
#3 0x5562f794d460 in _ZN10TcpSession5flushEv+0x60 (/usr/local/bin/snort @0x5562f7675000)
#4 0x5562f787b7ea in _ZN5snort4Flow5flushEb+0xca (/usr/local/bin/snort @0x5562f7675000)
#5 0x5562f787c4f1 in _ZN9FlowCache7releaseEPN5snort4FlowE11PruneReasonb+0x31 (/usr/local/bin/snort @0x5562f7675000)
#6 0x5562f793f548 in _ZN5snort6Stream17check_flow_closedEPNS_6PacketE+0xf8 (/usr/local/bin/snort @0x5562f7675000)
#7 0x5562f7853c8c in _ZN5snort15DetectionEngine14finish_inspectEPNS_6PacketEb+0x3c (/usr/local/bin/snort @0x5562f7675000)
#8 0x5562f7853d61 in _ZN5snort15DetectionEngine7inspectEPNS_6PacketE+0x41 (/usr/local/bin/snort @0x5562f7675000)
#9 0x5562f78caf21 in _ZL14process_packetPN5snort6PacketE+0xb1 (/usr/local/bin/snort @0x5562f7675000)
#10 0x5562f78cc0e4 in _ZN8Analyzer19process_daq_pkt_msgEPK8_daq_msgb+0xb4 (/usr/local/bin/snort @0x5562f7675000)
#11 0x5562f78cc388 in _ZN8Analyzer15process_daq_msgEPK8_daq_msgb+0x248 (/usr/local/bin/snort @0x5562f7675000)
#12 0x5562f78ccc96 in _ZN8Analyzer16process_messagesEv+0x1a6 (/usr/local/bin/snort @0x5562f7675000)
#13 0x5562f78ccfdb in _ZN8Analyzer7analyzeEv+0x5b (/usr/local/bin/snort @0x5562f7675000)
#14 0x5562f78cd1a1 in _ZN8AnalyzerclEP7Swappert+0xd1 (/usr/local/bin/snort @0x5562f7675000)
#15 0x7f74a3535d84 in _ZNKSt10error_code23default_error_conditionEv+0x34 (/lib/x86_64-linux-gnu/libstdc++.so.6 @0x7f74a345f000)
#16 0x7f74a3d14609 in start_thread+0xd9 (/lib/x86_64-linux-gnu/libpthread.so.0 @0x7f74a3d0b000)
#17 0x7f74a3223293 in clone+0x43 (/lib/x86_64-linux-gnu/libc.so.6 @0x7f74a3101000)
= Current DAQ Message (Type 1) =
== Header (48) ==
57a4 4860 0000 0000 0cec 0b00 0000 0000
3c00 0000 ffff ffff ffff ffff ffff ffff
0000 0000 0000 0000 0000 0000 0000 0000
== Data (60) ==
0000 0011 1111 0031 4619 bdbc 0800 4500
0028 2fab 4000 7d06 9a85 9c11 1f1c 5310
2562 0d3d e5f3 17e0 7d96 0b19 5f50 5014
0000 8920 0000 0000 0000 0000
</pre>

**Comment by snortadmin** [comment]
Hi - I think we have fixed that issue. That fix will be pushed here tomorrow.

**Comment by fatihusta** [comment]
I have a similar problem.

First
```
$snort -c /etc/snort/snort.lua --plugin-path /usr/lib64/snort3_extra -i ens18 -l /var/log/snort --create-pidfile -k none

....

pcap DAQ configured to passive.
Commencing packet processing
++ [0] ens18

Snort (PID 721316) caught fatal signal: SIGSEGV (11)
Version: 3.1.1.0

Backtrace:
  #0 0x7f594cb47a98
  #1 0x59588c in _ZN5snort7LogStatEPKcdP8_IO_FILE+0xdfc (snort @0x400000)
  #2 0x4f4fab in _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_St9_IdentityIS5_ESt4lessIS5_ESaIS5_EE17_M_emplace_uniqueIJRPKcEEESt4pairISt17_Rb_tree_iteratorIS5_EbEDpOT_+0xb8b (snort @0x400000)
  #3 0x44621e (snort @0x400000)
  #4 0x7f594cafa6a3 (/lib64/libc.so.6 @0x7f594cad7000)
  #5 0x459a8e in _start+0x2e (snort @0x400000)

Segmentation fault (core dumped)

```

Second 
I remove the --create-pidfile parameter
```
$ snort -c /etc/snort/snort.lua --plugin-path /usr/lib64/snort3_extra -i ens18 -l /var/log/snort -k none

........

pcap DAQ configured to passive.
Commencing packet processing
++ [0] ens18
FATAL: OpenAlertFile() => fopen() alert file /var/log/snort/alert_fast.txt: No such file or directory
Fatal Error, Quitting..

Snort (PID 721126) caught fatal signal: SIGABRT (6)
Version: 3.1.1.0

Backtrace:
  #0 0x7fd96fdba70f
  #1 0x7fd96fda4b25
  #2 0x435095
  #3 0x4d37b8 in _ZN5snort19CreateTCPFlagStringEPKNS_3tcp6TCPHdrEPc+0x138 (snort @0x400000)
  #4 0x4d7fcc in _ZN5snort12TextLog_InitEPKcjm+0x6c (snort @0x400000)
  #5 0x4dbee3 in _ZN5snort6Logger5alertEPNS_6PacketEPKcRK5Event+0x1b03 (snort @0x400000)
  #6 0x500932 in _ZN5snort5Codec16get_protocol_idsERSt6vectorI10ProtocolIdSaIS2_EE+0xab2 (snort @0x400000)
  #7 0x4e636d in _ZN3Lua11ManageStackD1Ev+0x169d (snort @0x400000)
  #8 0x4e6980 in _ZN3Lua11ManageStackD1Ev+0x1cb0 (snort @0x400000)
  #9 0x4e7f30 in _ZN5snort15DaqMessageEventD0Ev+0x210 (snort @0x400000)
  #10 0x4e7356 in _ZN3Lua11ManageStackD1Ev+0x2686 (snort @0x400000)
  #11 0x4e74fc in _ZN3Lua11ManageStackD1Ev+0x282c (snort @0x400000)
  #12 0x4e768d in _ZN3Lua11ManageStackD1Ev+0x29bd (snort @0x400000)
  #13 0x7fd9707a1b73 in _ZNKSt10error_code23default_error_conditionEv+0x33 (/lib64/libstdc++.so.6 @0x7fd9706df000)
  #14 0x7fd97318f2de (/lib64/libpthread.so.0 @0x7fd973187000)
  #15 0x7fd96fe7ee83 (/lib64/libc.so.6 @0x7fd96fd83000)

Aborted (core dumped)


```

workaround solution
mkdir -p /var/log/snort
