### ISSUE TITLE
snort crash issue with snort3-perf test on Arm64

### ISSUE THREAD

**Issue by Jianlin-lv** [snort3/snort3#182]
**Platform**:
$ lscpu
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          160
On-line CPU(s) list:             0-159
Thread(s) per core:              1
Core(s) per socket:              80
```

**Reproduce:**
```
export SNORT3_MIN_RULES=max.rules
export SNORT3_MAX_RULES=max.rules
export SNORT_ODP=/root/snort/snort3-perf
export SNORT_LUA_PATH=/usr/local/etc/snort/
/usr/local/bin/snort --warn-all --plugin-path /usr/local/lib64 --daq dump --daq-var output=none -H -Q -s 9000 -c inspect.lua -r ../defcon.pcap --lua 'search_engine.search_method = '\''ac_full'\''' -z 0 --pcap-loop 80
```

In the case of multi-threaded testing (more than 10 threads),  it is easier to reproduce.

**Summarize**:
1.	Disable AppID, the test is ok;
2.	we have observed crashes triggered by SIGSEGV (11) and SIGBUS (7);
3.	lua detector errors will occur probabilistically. LuaJIT(2.1.0-beta3) is not stable, so it is suspected that it may have issue;
4.	no exactly backtrace information from the core dump.

**Log:**

_SIGSEGV (11):_
```
Snort (PID 2116356) caught fatal signal: SIGSEGV (11)
Version: 3.1.4.0

Backtrace:

= Current DAQ Message (Type 1) =

== Header (48) ==
ab24 2a3f 0000 0000 1199 0700 0000 0000
5c00 0000 ffff ffff ffff ffff ffff ffff
0000 0000 0000 0000 0000 0000 0000 0000

== Data (92) ==
ffff ffff ffff 0030 6527 f2c7 0800 4500
004e 3485 0000 4011 93c4 c0a8 1106 c0a8
1fff c257 0089 003a dbaa 051a 0110 0001
0000 0000 0000 2041 4241 4346 5046 5045
4e46 4445 4346 4345 5046 4846 4445 4646
5046 5041 4341 4200 0020 0001

Segmentation fault (core dumped)

```
_SIGBUS (7):_
```
lua detector odp_client_netbios-ns.lua: error validating /root/snort/snort3-perf/odp/lua/client_netbios-ns.lua:0: attempt to index global 'detectorFlow' (a nil value)
WARNING: appid: no lua detectors found in directory '/root/snort/snort3-perf/custom/lua/*'
WARNING: appid: no lua detectors found in directory '/root/snort/snort3-perf/custom/lua/*'
lua detector odp_client_netbios-ns.lua: error validating /root/snort/snort3-perf/odp/lua/client_netbios-ns.lua:0: attempt to index global 'detectorFlow' (a nil value)

Snort (PID 1834071) caught fatal signal: SIGBUS (7)
Version: 3.1.4.0

Backtrace:

= Current DAQ Message (Type 1) =

== Header (48) ==
0b25 2a3f 0000 0000 274f 0200 0000 0000
5c00 0000 ffff ffff ffff ffff ffff ffff
0000 0000 0000 0000 0000 0000 0000 0000

== Data (92) ==
ffff ffff ffff 0040 9637 7043 0800 4500
004e 001c 0000 8011 6a1a 4545 4525 45ff
ffff 0089 0089 003a 5e8c 8004 0110 0001
0000 0000 0000 2046 4846 4145 4245 4543
4f43 4143 4143 4143 4143 4143 4143 4143
4143 4143 4141 4100 0020 0001
```

_Core dump:_

```
(gdb) file /usr/local/bin/snort
Reading symbols from /usr/local/bin/snort...
(gdb) bt
#0  0x0000ffffb1f5efb4 in ?? ()
#1  0x000051c3a13723d8 in ?? ()
Backtrace stopped: not enough registers or memory available to unwind further
(gdb)
```

The backtrace is obtained under enable debugging options.
               "./Configure_cmake.sh --prefix=/usr/local --enable-tcmalloc --enable-debug"

The stack may be destroyed somewhere, resulting in not getting a valid stack frame.

Other:
```
# snort -V

   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.1.4.0
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2021 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.0
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 1.1.1f  31 Mar 2020
           Using libpcap version 1.9.1 (with TPACKET_V3)
           Using PCRE version 8.44 2020-02-12
           Using ZLIB version 1.2.11
           Using FlatBuffers 1.12.0
           Using Hyperscan version 5.4.2 2021-04-29
           Using LZMA version 5.2.4
```

**Comment by snortadmin** [comment]
Hi - have you tried 2.0.5? We haven't tested with the beta version.

**Comment by Jianlin-lv** [comment]
> Hi - have you tried 2.0.5? We haven't tested with the beta version.

I haven't tested 2.0.5,   I can try to do it.

Which ones belong to the beta version?
My test version is 3.1.4.0.
