### ISSUE TITLE
snort3 segfault during shutting down

### ISSUE THREAD

**Issue by chxdeng** [snort3/snort3#222]
Observed snort3 segfault during process shutting down

snort --version

   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.1.16.0
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2021 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 3.0.5
           Using LuaJIT version 2.1.0-beta3
           Using OpenSSL 1.1.1f  31 Mar 2020
           Using libpcap version 1.9.1 (with TPACKET_V3)
           Using PCRE version 8.45 2021-06-15
           Using ZLIB version 1.2.11
           Using LZMA version 5.2.4

#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x0000555622044ee9 in get_so_api (soid=0x55562c412830 "22089", so_rules=0x555622f6f5d0)
    at /work/snort3-3.1.16.0/src/managers/so_manager.cc:194
#2  0x00005556220451ea in SoManager::delete_so_data (soid=<optimized out>, 
    pv=0x55562c413000, so_rules=<optimized out>)
    at /work/snort3-3.1.16.0/src/managers/so_manager.cc:226
#3  0x0000555621fef753 in SoOption::~SoOption (this=0x55562c411340, 
    __in_chrg=<optimized out>) at /work/snort3-3.1.16.0/src/ips_options/ips_so.cc:78
#4  SoOption::~SoOption (this=0x55562c411340, __in_chrg=<optimized out>)
    at /work/snort3-3.1.16.0/src/ips_options/ips_so.cc:79
#5  0x0000555621fcf6ab in snort::XHash::delete_hash_table (this=this@entry=0x555622f80510)
    at /work/snort3-3.1.16.0/src/hash/xhash.cc:174
#6  0x0000555621f98527 in DetectionOptionHash::~DetectionOptionHash (this=0x555622f80510, 
    __in_chrg=<optimized out>)
    at /work/snort3-3.1.16.0/src/detection/detection_options.cc:136
#7  DetectionOptionHash::~DetectionOptionHash (this=0x555622f80510, 
    __in_chrg=<optimized out>)
    at /work/snort3-3.1.16.0/src/detection/detection_options.cc:137
#8  0x0000555621f99d28 in fpDeleteFastPacketDetection (sc=0x555622f6f970)
    at /work/snort3-3.1.16.0/src/detection/fp_create.cc:1656
#9  0x0000555622023ea9 in snort::SnortConfig::~SnortConfig (this=0x555622f6f970, 
    __in_chrg=<optimized out>) at /work/snort3-3.1.16.0/src/main/snort_config.cc:241
#10 0x0000555622021114 in snort::Snort::term ()
    at /work/snort3-3.1.16.0/src/main/snort.cc:355
#11 0x000055562202198d in snort::Snort::term ()
--Type <RET> for more, q to quit, c to continue without paging--c
    at /work/snort3-3.1.16.0/src/main/snort.cc:430
#12 snort::Snort::clean_exit () at /work/snort3-3.1.16.0/src/main/snort.cc:372
#13 snort::Snort::cleanup () at /work/snort3-3.1.16.0/src/main/snort.cc:430
#14 0x0000555621f6c768 in main (argc=<optimized out>, argv=<optimized out>) at /work/snort3-3.1.16.0/src/main.cc:1141

**Comment by chxdeng** [comment]
This could be due to the updated so binaries during restart.
Closing the ticket.
