### ISSUE TITLE
Snort3 caught fatal signal

### ISSUE THREAD

**Issue by y-shevchenko** [snort3/snort3#270]
syslog:

```
Sep 26 01:55:28 f-ch30-179 snort[28885]: Version: 3.1.32.0
Sep 26 01:55:28 f-ch30-179 snort[28885]: Backtrace:
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #0 0x558c20e086d6 in _ZN5snort10SearchTool8find_allEPKcjPFiPvS3_iS3_S3_EbS3_+0x1186 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #1 0x558c20e07772 in _ZN5snort10SearchTool8find_allEPKcjPFiPvS3_iS3_S3_EbS3_+0x222 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #2 0x558c20d53200 in _ZN5snort4Mpse7_searchERNS_9MpseBatchENS0_8MpseTypeE+0x90 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #3 0x558c20d533eb in _ZN5snort4Mpse7set_optEi+0x8b (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #4 0x558c20d25d88 in _ZNK5snort4Mpse17get_pattern_countEv+0x2538 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #5 0x558c20d1de2a in _ZN5snort15DetectionEngine7offloadEPNS_6PacketE+0x14a (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #6 0x558c20d1e357 in _ZN5snort15DetectionEngine7inspectEPNS_6PacketE+0xc7 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #7 0x558c20d96500 in _ZN8Analyzer15inspect_rebuiltEPN5snort6PacketE+0x20 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #8 0x558c20e1c50b in _ZN5snort11LogSplitterD0Ev+0xa07b (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #9 0x558c20e1da55 in _ZN5snort11LogSplitterD0Ev+0xb5c5 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #10 0x558c20e21bfc in _ZNSt6vectorIPFvPN5snort10IpsContextEESaIS4_EE17_M_realloc_insertIJRS4_EEEvN9__gnu_cxx17__normal_iteratorIPS4_S6_EEDpOT_+0x3f8c (snort @0x558c20c2>
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #11 0x558c20e234f5 in _ZNSt6vectorIPFvPN5snort10IpsContextEESaIS4_EE17_M_realloc_insertIJRS4_EEEvN9__gnu_cxx17__normal_iteratorIPS4_S6_EEDpOT_+0x5885 (snort @0x558c20c2>
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #12 0x558c20e20da1 in _ZNSt6vectorIPFvPN5snort10IpsContextEESaIS4_EE17_M_realloc_insertIJRS4_EEEvN9__gnu_cxx17__normal_iteratorIPS4_S6_EEDpOT_+0x3131 (snort @0x558c20c2>
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #13 0x558c20dbeb94 in _ZNSt8__detail9_Map_baseItSt4pairIKtPN5snort9InspectorEESaIS6_ENS_10_Select1stESt8equal_toItESt4hashItENS_18_Mod_range_hashingENS_20_Default_range>
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #14 0x558c20d1e31e in _ZN5snort15DetectionEngine7inspectEPNS_6PacketE+0x8e (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #15 0x558c20d97ce3 in _ZN8Analyzer15inspect_rebuiltEPN5snort6PacketE+0x1803 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #16 0x558c20d97ede in _ZN8Analyzer15inspect_rebuiltEPN5snort6PacketE+0x19fe (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #17 0x558c20d98289 in _ZN8Analyzer15inspect_rebuiltEPN5snort6PacketE+0x1da9 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #18 0x558c20d9850b in _ZN8Analyzer15inspect_rebuiltEPN5snort6PacketE+0x202b (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #19 0x558c20d98693 in _ZN8Analyzer15inspect_rebuiltEPN5snort6PacketE+0x21b3 (snort @0x558c20c21000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #20 0x7f3c44e41ed0 in _ZNKSt10error_code23default_error_conditionEv+0x30 (/lib/x86_64-linux-gnu/libstdc++.so.6 @0x7f3c44d73000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #21 0x7f3c45651ea7 in start_thread+0xd7 (/lib/x86_64-linux-gnu/libpthread.so.0 @0x7f3c4564a000)
Sep 26 01:55:28 f-ch30-179 snort[28885]:   #22 0x7f3c44b3aaef in clone+0x3f (/lib/x86_64-linux-gnu/libc.so.6 @0x7f3c44a3e000)
Sep 26 01:55:28 f-ch30-179 snort[28885]: = Current DAQ Message (Type 1) =
Sep 26 01:55:28 f-ch30-179 snort[28885]: == Header (56) ==
Sep 26 01:55:28 f-ch30-179 snort[28885]: d03e 3163 0000 0000 6780 0100 0000 0000
Sep 26 01:55:28 f-ch30-179 snort[28885]: d501 0000 0200 0000 0200 0000 ffff ffff
Sep 26 01:55:28 f-ch30-179 snort[28885]: 0000 0000 0000 0000 0000 0000 0000 0000
Sep 26 01:55:28 f-ch30-179 snort[28885]: 0000 0000 0000 0000
Sep 26 01:55:28 f-ch30-179 snort[28885]: == Data (469) ==
Sep 26 01:55:28 f-ch30-179 snort[28885]: 4500 01d5 dee0 4000 f006 4209 c73b f3de
Sep 26 01:55:28 f-ch30-179 snort[28885]: ac10 010e 0050 9f98 79c3 1407 27d2 5d71
Sep 26 01:55:28 f-ch30-179 snort[28885]: 5018 0209 a319 0000 4854 5450 2f31 2e31
Sep 26 01:55:28 f-ch30-179 snort[28885]: 2034 3033 2046 6f72 6269 6464 656e 0d0a
Sep 26 01:55:28 f-ch30-179 snort[28885]: 5365 7276 6572 3a20 6f70 656e 7265 7374
Sep 26 01:55:28 f-ch30-179 snort[28885]: 790d 0a44 6174 653a 204d 6f6e 2c20 3236
Sep 26 01:55:28 f-ch30-179 snort[28885]: 2053 6570 2032 3032 3220 3035 3a35 353a
Sep 26 01:55:28 f-ch30-179 snort[28885]: 3238 2047 4d54 0d0a 436f 6e74 656e 742d
Sep 26 01:55:28 f-ch30-179 snort[28885]: 5479 7065 3a20 7465 7874 2f68 746d 6c3b
Sep 26 01:55:28 f-ch30-179 snort[28885]: 2063 6861 7273 6574 3d75 7466 2d38 0d0a
Sep 26 01:55:28 f-ch30-179 snort[28885]: 5472 616e 7366 6572 2d45 6e63 6f64 696e
Sep 26 01:55:28 f-ch30-179 snort[28885]: 673a 2063 6875 6e6b 6564 0d0a 436f 6e6e
Sep 26 01:55:28 f-ch30-179 snort[28885]: 6563 7469 6f6e 3a20 6b65 6570 2d61 6c69
Sep 26 01:55:28 f-ch30-179 snort[28885]: 7665 0d0a 782d 6261 636b 656e 642d 7365
Sep 26 01:55:28 f-ch30-179 snort[28885]: 7276 6572 3a20 6970 2d31 302d 3230 312d
Sep 26 01:55:28 f-ch30-179 snort[28885]: 3136 2d32 3431 2e65 6332 2e69 6e74 6572
Sep 26 01:55:28 f-ch30-179 snort[28885]: 6e61 6c0d 0a43 6f6e 7465 6e74 2d45 6e63
Sep 26 01:55:28 f-ch30-179 snort[28885]: 6f64 696e 673a 2067 7a69 700d 0a0d 0a61
Sep 26 01:55:28 f-ch30-179 snort[28885]: 620d 0a1f 8b08 0000 0000 0004 03ed 90b1
Sep 26 01:55:28 f-ch30-179 snort[28885]: 0a02 3110 447b c17f 583f 2044 d172 4923
Sep 26 01:55:28 f-ch30-179 snort[28885]: 0a16 567e 41e2 ae97 402e 39f6 d2dc df9b
Sep 26 01:55:28 f-ch30-179 snort[28885]: e81d 88b5 a5e5 cebc 1986 455f fa68 d62b
Sep 26 01:55:28 f-ch30-179 snort[28885]: f46c c960 0925 b239 6cf7 70ce e202 1127
Sep 26 01:55:28 f-ch30-179 snort[28885]: d46f 11f5 0ba9 a8cb 34b5 c89d 5361 31e8
Sep 26 01:55:28 f-ch30-179 snort[28885]: 77df 89aa a09e edd6 5da1 f9ca 0327 e1b1
Sep 26 01:55:28 f-ch30-179 snort[28885]: 4c9f be5e 1af5 b266 a314 5818 2c51 481d
Sep 26 01:55:28 f-ch30-179 snort[28885]: 940c 1446 eb22 c3f5 7639 814d 0447 2fb9
Sep 26 01:55:28 f-ch30-179 snort[28885]: 6778 48e0 4471 0216 c952 131d 8352 6ddd
Sep 26 01:55:28 f-ch30-179 snort[28885]: bfe2 97bf 7802 4e40 052c 2802 0000 0d0a
Sep 26 01:55:28 f-ch30-179 snort[28885]: 300d 0a0d 0a
Sep 26 01:55:28 f-ch30-179 systemd[1]: snort3.service: Main process exited, code=killed, status=11/SEGV
Sep 26 01:55:28 f-ch30-179 systemd[1]: snort3.service: Failed with result 'signal'.
```
Config start 
`snort -c /usr/local/etc/snort/snort.lua -Q -D -l /var/log/snort -z 0`

Snort.lua:
```
---------------------------------------------------------------------------
-- Snort++ configuration
---------------------------------------------------------------------------

-- there are over 200 modules available to tune your policy.
-- many can be used with defaults w/o any explicit configuration.
-- use this conf as a template for your specific configuration.

-- 1. configure defaults
-- 2. configure inspection
-- 3. configure bindings
-- 4. configure performance
-- 5. configure detection
-- 6. configure filters
-- 7. configure outputs
-- 8. configure tweaks

---------------------------------------------------------------------------
-- 1. configure defaults
---------------------------------------------------------------------------

-- HOME_NET and EXTERNAL_NET must be set now
-- setup the network addresses you are protecting
HOME_NET = '192.168.0.0/16'

-- set up the external network addresses.
-- (leave as "any" in most situations)
EXTERNAL_NET = 'any'

include 'snort_defaults.lua'
include 'file_magic.lua'
include 'inline.lua'
---------------------------------------------------------------------------
-- 2. configure inspection
---------------------------------------------------------------------------

-- mod = { } uses internal defaults
-- you can see them with snort --help-module mod

-- mod = default_mod uses external defaults
-- you can see them in snort_defaults.lua

-- the following are quite capable with defaults:

stream = { }
stream_ip = { }
stream_icmp = { }
stream_tcp = { }
stream_udp = { }
stream_user = { }
stream_file = { }

arp_spoof = { }
back_orifice = { }
dns = { }
imap = { }
netflow = {}
normalizer = { }
pop = { }
rpc_decode = { }
sip = { }
ssh = { }
ssl = { }
telnet = { }

cip = { }
dnp3 = { }
iec104 = { }
mms = { }
modbus = { }
s7commplus = { }

dce_smb = { }
dce_tcp = { }
dce_udp = { }
dce_http_proxy = { }
dce_http_server = { }

-- see snort_defaults.lua for default_*
gtp_inspect = default_gtp
port_scan = default_med_port_scan
smtp = default_smtp

ftp_server = default_ftp_server
ftp_client = { }
ftp_data = { }

http_inspect = default_http_inspect
http2_inspect = { }

-- see file_magic.lua for file id rules
file_id = { file_rules = file_magic }
file_policy = { }

-- the following require additional configuration to be fully effective:


appid =
{
    app_detector_dir = '/usr/local/lib',
    -- appid requires this to use appids in rules
    --app_detector_dir = 'directory to load appid detectors from'
}

--[[
reputation =
{
    -- configure one or both of these, then uncomment reputation
    -- (see also related path vars at the top of snort_defaults.lua)

    --blacklist = 'blacklist file name with ip lists'
    --whitelist = 'whitelist file name with ip lists'
}
--]]

---------------------------------------------------------------------------
-- 3. configure bindings
---------------------------------------------------------------------------

wizard = default_wizard

binder =
{
    -- port bindings required for protocols without wizard support
    { when = { proto = 'udp', ports = '53', role='server' },  use = { type = 'dns' } },
    { when = { proto = 'tcp', ports = '53', role='server' },  use = { type = 'dns' } },
    { when = { proto = 'tcp', ports = '102', role = 'server' }, use = { type = 's7commplus' } },
    { when = { proto = 'tcp', ports = '111', role='server' }, use = { type = 'rpc_decode' } },
    { when = { proto = 'tcp', ports = '502', role='server' }, use = { type = 'modbus' } },
    { when = { proto = 'tcp', ports = '2123 2152 3386', role='server' }, use = { type = 'gtp_inspect' } },
    { when = { proto = 'tcp', ports = '2404', role='server' }, use = { type = 'iec104' } },
    { when = { proto = 'udp', ports = '22222', role = 'server' }, use = { type = 'cip' } },
    { when = { proto = 'tcp', ports = '44818', role = 'server' }, use = { type = 'cip' } },

    { when = { proto = 'tcp', service = 'dcerpc' },  use = { type = 'dce_tcp' } },
    { when = { proto = 'udp', service = 'dcerpc' },  use = { type = 'dce_udp' } },
    { when = { proto = 'udp', service = 'netflow' }, use = { type = 'netflow' } },

    { when = { service = 'netbios-ssn' },      use = { type = 'dce_smb' } },
    { when = { service = 'dce_http_server' },  use = { type = 'dce_http_server' } },
    { when = { service = 'dce_http_proxy' },   use = { type = 'dce_http_proxy' } },

    { when = { service = 'cip' },              use = { type = 'cip' } },
    { when = { service = 'dnp3' },             use = { type = 'dnp3' } },
    { when = { service = 'dns' },              use = { type = 'dns' } },
    { when = { service = 'ftp' },              use = { type = 'ftp_server' } },
    { when = { service = 'ftp-data' },         use = { type = 'ftp_data' } },
    { when = { service = 'gtp' },              use = { type = 'gtp_inspect' } },
    { when = { service = 'imap' },             use = { type = 'imap' } },
    { when = { service = 'http' },             use = { type = 'http_inspect' } },
    { when = { service = 'http2' },            use = { type = 'http2_inspect' } },
    { when = { service = 'iec104' },           use = { type = 'iec104' } },
    { when = { service = 'mms' },              use = { type = 'mms' } },
    { when = { service = 'modbus' },           use = { type = 'modbus' } },
    { when = { service = 'pop3' },             use = { type = 'pop' } },
    { when = { service = 'ssh' },              use = { type = 'ssh' } },
    { when = { service = 'sip' },              use = { type = 'sip' } },
    { when = { service = 'smtp' },             use = { type = 'smtp' } },
    { when = { service = 'ssl' },              use = { type = 'ssl' } },
    { when = { service = 'sunrpc' },           use = { type = 'rpc_decode' } },
    { when = { service = 's7commplus' },       use = { type = 's7commplus' } },
    { when = { service = 'telnet' },           use = { type = 'telnet' } },

    { use = { type = 'wizard' } }
}

---------------------------------------------------------------------------
-- 4. configure performance
---------------------------------------------------------------------------

-- use latency to monitor / enforce packet and rule thresholds
--latency = { }

-- use these to capture perf data for analysis and tuning
--profiler = { }
--perf_monitor = { }

---------------------------------------------------------------------------
-- 5. configure detection
---------------------------------------------------------------------------


references = default_references
classifications = default_classifications

ips =
{
   mode = inline,
    -- use this to enable decoder and inspector alerts
    --enable_builtin_rules = true,

    -- use include for rules files; be sure to set your path
    -- note that rules files can include other rules files
    -- (see also related path vars at the top of snort_defaults.lua)

   variables = default_variables,
   rules = [[
        include $RULE_PATH/torrent.rules
        include $RULE_PATH/custom_malware.rules
    ]]

}

-- use these to configure additional rule actions
-- react = { }
-- reject = { }

-- use this to enable payload injection utility
-- payload_injector = { }

---------------------------------------------------------------------------
-- 6. configure filters
---------------------------------------------------------------------------

-- below are examples of filters
-- each table is a list of records

--[[
suppress =
{
    -- don't want to any of see these
    { gid = 1, sid = 1 },

    -- don't want to see anything for a given host
    { track = 'by_dst', ip = '1.2.3.4' }

    -- don't want to see these for a given host
    { gid = 1, sid = 2, track = 'by_dst', ip = '1.2.3.4' },
}
--]]

--[[
event_filter =
{
    -- reduce the number of events logged for some rules
    { gid = 1, sid = 1, type = 'limit', track = 'by_src', count = 2, seconds = 10 },
    { gid = 1, sid = 2, type = 'both',  track = 'by_dst', count = 5, seconds = 60 },
}
--]]

--[[
rate_filter =
{
    -- alert on connection attempts from clients in SOME_NET
    { gid = 135, sid = 1, track = 'by_src', count = 5, seconds = 1,
      new_action = 'alert', timeout = 4, apply_to = '[$SOME_NET]' },

    -- alert on connections to servers over threshold
    { gid = 135, sid = 2, track = 'by_dst', count = 29, seconds = 3,
      new_action = 'alert', timeout = 1 },
}
--]]

---------------------------------------------------------------------------
-- 7. configure outputs
---------------------------------------------------------------------------

-- event logging
-- you can enable with defaults from the command line with -A <alert_type>
-- uncomment below to set non-default configs
--alert_csv = { }
--alert_fast = { }
--alert_fast = { 
--        file = true, 
--        packet = false,
--        limit = 10,
--}
--alert_full = { }
--alert_sfsocket = { }
--alert_syslog = { }
--unified2 = { }

-- packet logging
-- you can enable with defaults from the command line with -L <log_type>
--log_codecs = { }
--log_hext = { }
--log_pcap = { }

-- additional logs
--packet_capture = { }
--file_log = { }

---------------------------------------------------------------------------
-- 8. configure tweaks
---------------------------------------------------------------------------

if ( tweaks ~= nil ) then
    include(tweaks .. '.lua')
end
```

Inline.lua:

```
---------------------------------------------------------------------------
-- inline test tweaks
-- use with --tweaks inline
---------------------------------------------------------------------------

daq =
{
    inputs = { '1' },
    modules =
    {
        {
            name = 'nfq',
            mode = 'inline'
        }
    }
}
```

**Comment by ansrb** [comment]
Hi, thank you for the report.
Is this a recurring issue or was it a one time thing? If this is recurring we would appreciate more information about reproduction steps. I see that you have shared your configuration and a backtrace, but this is sadly not enough for an extensive investigation. It would really help if you could answer some of these questions.
Firstly, the backtrace seems to be mangled and doesn't tell much. To be readable it would have to be generated on a debug build. Also, a core file would be ideal if you happened to have one.
Do you maybe still have the traffic that caused this crash saved somewhere? It would be really helpful to have it for the investigation.
And the last thing, I see that in your configuration you are importing some custom rules. What rules are those exactly?
