### ISSUE TITLE
Segmentation fault when appid is configured

### ISSUE THREAD

**Issue by ymansour** [snort3/snort3#58]
Snort 3 Beta faults when appid is configured.

snort_default.lua
```
APPID_PATH = '/usr/local/snort/appid'
```
snort.lua
```
appid =
{
    app_detector_dir = APPID_PATH,
    log_stats = true
}
```
appid version: 8373 or
```
# cat odp/version.conf 
VERSION=303
```

```
-- [2] ./pcaps/fuzz-2006-07-06-20811.pcap
++ [2] ./pcaps/fuzz-2006-07-09-13403.pcap
[Thread 0x7ffff2802700 (LWP 21563) exited]
[New Thread 0x7ffff2802700 (LWP 21567)]
#0  0x00007ffff647c1b0 in ?? () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00007ffff647d861 in lua_rawgeti () from /usr/local/lib/libluajit-5.1.so.2
#2  0x00007ffff64b4e79 in luaL_unref () from /usr/local/lib/libluajit-5.1.so.2
#3  0x00000000006b26fe in free_detector_flow (userdata=0xcef81f0) at /root/sources/snort3/src/network_inspectors/appid/lua_detector_flow_api.cc:235
#4  0x0000000000673681 in snort::sflist_static_free_all (s=0x7ffff2ff0948, nfree=0x6b26bb <free_detector_flow(void*)>) at /root/sources/snort3/src/utils/sflsq.cc:294
#5  0x00000000006b3258 in LuaDetectorManager::~LuaDetectorManager (this=0x7fffef38d350, __in_chrg=<optimized out>) at /root/sources/snort3/src/network_inspectors/appid/lua_detector_module.cc:193
#6  0x00000000006b338b in LuaDetectorManager::terminate () at /root/sources/snort3/src/network_inspectors/appid/lua_detector_module.cc:219
#7  0x000000000069e7b3 in AppIdInspector::tterm (this=0x1ee1aa0) at /root/sources/snort3/src/network_inspectors/appid/appid_inspector.cc:172
#8  0x00000000005d9304 in snort::InspectorManager::thread_stop () at /root/sources/snort3/src/managers/inspector_manager.cc:664
#9  0x00000000005c742b in snort::Snort::thread_term () at /root/sources/snort3/src/main/snort.cc:824
#10 0x00000000005b1373 in Analyzer::operator() (this=0x15b63210, ps=0xfb0f480, run_num=7) at /root/sources/snort3/src/main/analyzer.cc:101
#11 0x000000000052954e in std::__invoke<Analyzer<Swapper*, unsigned short> > (__f=...) at /usr/include/c++/4.8.2/functional:234
#12 0x00000000005294ed in std::reference_wrapper<Analyzer>::operator()<Swapper*, unsigned short>(Swapper*&&, unsigned short&&) const (this=0x105544d0) at /usr/include/c++/4.8.2/functional:467
#13 0x0000000000529451 in std::_Bind_simple<std::reference_wrapper<Analyzer> (Swapper*, unsigned short)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=0x105544c0) at /usr/include/c++/4.8.2/functional:1732
#14 0x0000000000529309 in std::_Bind_simple<std::reference_wrapper<Analyzer> (Swapper*, unsigned short)>::operator()() (this=0x105544c0) at /usr/include/c++/4.8.2/functional:1720
#15 0x00000000005292a2 in std::thread::_Impl<std::_Bind_simple<std::reference_wrapper<Analyzer> (Swapper*, unsigned short)> >::_M_run() (this=0x105544a8) at /usr/include/c++/4.8.2/thread:115
#16 0x00007ffff528b070 in ?? () from /lib64/libstdc++.so.6
#17 0x00007ffff6b42e25 in start_thread () from /lib64/libpthread.so.0
#18 0x00007ffff49efbad in clone () from /lib64/libc.so.6
```

**Comment by rvshravan** [comment]
The issue is with ODP detector service_tftp.lua. If this issue is blocking your work, please move that detector out of the ODP. We will be fixing this issue in a future ODP release. Thanks for reporting it!

**Comment by ymansour** [comment]
Thanks for the update, I can confirm that the fault does not occur after moving the service_tftp.lua out of ODP. Out of curiosity, will this and the other reported faults have CVEs assigned?

**Comment by prashinde** [comment]
We modified AppId Engine code to be more robust so it does not crash on invalid lua detectors

**Comment by snortadmin** [comment]
Let us know if this fixes the issue for you w/o removing service_tftp.lua.

Thanks
Russ

**Comment by ymansour** [comment]
Russ,

Yes, it fixes the issue.

prashinde,

Thank you.

**Comment by snortadmin** [comment]
Awesome, thanks for reporting it.

Russ
