### ISSUE TITLE
Segmentation fault on dce_rpc inspector

### ISSUE THREAD

**Issue by ymansour** [snort3/snort3#59]
Snort 3 Beta faults with below. Snort does not fault when dce_rpc inspector/binder is disabled.

```
[New Thread 0x7ffff2802700 (LWP 14180)]
-- [3] ./pcaps/fuzz-2010-06-26-12232.pcap
++ [3] ./pcaps/fuzz-2010-06-27-1544.pcap
[Thread 0x7ffff2001700 (LWP 14178) exited]
[New Thread 0x7ffff2001700 (LWP 14181)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3003700 (LWP 14176)]
0x000000000075e8a8 in DCE2_CoSetRopts (sd=0x38760b78, cot=0x38760bd8, co_hdr=0x3db1a010, p=0x7fffede20c40) at /root/sources/snort3/src/service_inspectors/dce_rpc/dce_co.cc:298
298	    endianness->hdr_byte_order = DceRpcCoByteOrder(co_hdr);
#0  0x000000000075e8a8 in DCE2_CoSetRopts (sd=0x38760b78, cot=0x38760bd8, co_hdr=0x3db1a010, p=0x7fffede20c40) at /root/sources/snort3/src/service_inspectors/dce_rpc/dce_co.cc:298
#1  0x0000000000760720 in DCE2_CoRequest (sd=0x38760b78, cot=0x38760bd8, co_hdr=0x3db1a010, frag_ptr=0x3db1a028 "\001", frag_len=132) at /root/sources/snort3/src/service_inspectors/dce_rpc/dce_co.cc:1529
#2  0x0000000000760e24 in DCE2_CoDecode (sd=0x38760b78, cot=0x38760bd8, frag_ptr=0x3db1a020 "\204", frag_len=140) at /root/sources/snort3/src/service_inspectors/dce_rpc/dce_co.cc:1816
#3  0x000000000076199e in DCE2_CoProcess (sd=0x38760b78, cot=0x38760bd8, data_ptr=0x3db1a0ac "\005", data_len=156) at /root/sources/snort3/src/service_inspectors/dce_rpc/dce_co.cc:2301
#4  0x0000000000775124 in Dce2Tcp::eval (this=0x5cf66d0, p=0x7fffede20b50) at /root/sources/snort3/src/service_inspectors/dce_rpc/dce_tcp.cc:170
#5  0x00000000005d9e4a in snort::InspectorManager::full_inspection (p=0x7fffede20b50) at /root/sources/snort3/src/managers/inspector_manager.cc:944
#6  0x00000000005da08a in snort::InspectorManager::execute (p=0x7fffede20b50) at /root/sources/snort3/src/managers/inspector_manager.cc:1006
#7  0x000000000052f497 in snort::DetectionEngine::inspect (p=0x7fffede20b50) at /root/sources/snort3/src/detection/detection_engine.cc:403
#8  0x00000000005c75b2 in snort::Snort::inspect (p=0x7fffede20b50) at /root/sources/snort3/src/main/snort.cc:868
#9  0x00000000006594cd in TcpReassembler::_flush_to_seq (this=0x135c458 <TcpReassemblerFactory::create(StreamPolicy)::bsd>, trs=..., bytes=312, p=0x7fffede20c40, pkt_flags=128) at /root/sources/snort3/src/stream/tcp/tcp_reassembler.cc:563
#10 0x00000000006597f4 in TcpReassembler::flush_to_seq (this=0x135c458 <TcpReassemblerFactory::create(StreamPolicy)::bsd>, trs=..., bytes=312, p=0x7fffede20c40, pkt_flags=128) at /root/sources/snort3/src/stream/tcp/tcp_reassembler.cc:623
#11 0x0000000000659d13 in TcpReassembler::flush_stream (this=0x135c458 <TcpReassemblerFactory::create(StreamPolicy)::bsd>, trs=..., p=0x7fffede20c40, dir=128, final_flush=true) at /root/sources/snort3/src/stream/tcp/tcp_reassembler.cc:742
#12 0x0000000000659d92 in TcpReassembler::final_flush (this=0x135c458 <TcpReassemblerFactory::create(StreamPolicy)::bsd>, trs=..., p=0x7fffede20c40, dir=128) at /root/sources/snort3/src/stream/tcp/tcp_reassembler.cc:754
#13 0x000000000065a08d in TcpReassembler::flush_queued_segments (this=0x135c458 <TcpReassemblerFactory::create(StreamPolicy)::bsd>, trs=..., flow=0x256c33b8, clear=true, p=0x7fffede20c40) at /root/sources/snort3/src/stream/tcp/tcp_reassembler.cc:808
#14 0x000000000065fc95 in TcpReassemblerPolicy::flush_queued_segments (this=0x7fffec7745d8, flow=0x256c33b8, clear=true, p=0x0) at /root/sources/snort3/src/stream/tcp/tcp_reassemblers.h:56
#15 0x000000000065cedc in TcpSession::clear_session (this=0x7fffec774310, free_flow_data=true, flush_segments=true, restart=false, p=0x0) at /root/sources/snort3/src/stream/tcp/tcp_session.cc:157
#16 0x000000000064f3fc in TcpStreamSession::cleanup (this=0x7fffec774310, p=0x0) at /root/sources/snort3/src/stream/libtcp/tcp_stream_session.cc:414
#17 0x000000000055ca07 in snort::Flow::reset (this=0x256c33b8, do_cleanup=true) at /root/sources/snort3/src/flow/flow.cc:138
#18 0x000000000055dd68 in FlowCache::release (this=0x38b37e90, flow=0x256c33b8, reason=IDLE, do_cleanup=true) at /root/sources/snort3/src/flow/flow_cache.cc:152
#19 0x000000000055e2ba in FlowCache::timeout (this=0x38b37e90, num_flows=1, thetime=1268520507) at /root/sources/snort3/src/flow/flow_cache.cc:318
#20 0x000000000055e9b7 in FlowControl::timeout_flows (this=0x7fffeed6d690, cur_time=1268520507) at /root/sources/snort3/src/flow/flow_control.cc:148
#21 0x0000000000643b1e in snort::Stream::timeout_flows (cur_time=1268520507) at /root/sources/snort3/src/stream/stream.cc:367
#22 0x00000000005c7b05 in snort::Snort::packet_callback (pkthdr=0x7ffff2fcc5e0, pkt=0x3dee3800 "\377\377\377\377\377\377") at /root/sources/snort3/src/main/snort.cc:1015
#23 0x000000000079f231 in pcap_process_loop (user=user@entry=0x7fffec1bb4a0 "", pkth=pkth@entry=0x7ffff2fcc690, data=0x3dee3800 "\377\377\377\377\377\377") at daq_pcap.c:376
#24 0x00007ffff759b0d1 in pcap_offline_read (p=0x3c6962c0, cnt=-1, callback=0x79f1a0 <pcap_process_loop>, user=0x7fffec1bb4a0 "") at ./savefile.c:506
#25 0x000000000079f35b in pcap_daq_acquire (handle=0x7fffec1bb4a0, cnt=0, callback=<optimized out>, metaback=<optimized out>, user=<optimized out>) at daq_pcap.c:394
#26 0x00000000005fdcd9 in snort::SFDAQInstance::acquire (this=0x969d2a0, max=0, callback=0x5c791c <snort::Snort::packet_callback(void*, _daq_pkthdr const*, unsigned char const*)>) at /root/sources/snort3/src/packet_io/sfdaq.cc:570
#27 0x00000000005b157a in Analyzer::analyze (this=0x5e62370) at /root/sources/snort3/src/main/analyzer.cc:161
#28 0x00000000005b136e in Analyzer::operator() (this=0x5e62370, ps=0xcf02610, run_num=413) at /root/sources/snort3/src/main/analyzer.cc:99
#29 0x000000000052954e in std::__invoke<Analyzer<Swapper*, unsigned short> > (__f=...) at /usr/include/c++/4.8.2/functional:234
#30 0x00000000005294ed in std::reference_wrapper<Analyzer>::operator()<Swapper*, unsigned short>(Swapper*&&, unsigned short&&) const (this=0x35287670) at /usr/include/c++/4.8.2/functional:467
#31 0x0000000000529451 in std::_Bind_simple<std::reference_wrapper<Analyzer> (Swapper*, unsigned short)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=0x35287660) at /usr/include/c++/4.8.2/functional:1732
#32 0x0000000000529309 in std::_Bind_simple<std::reference_wrapper<Analyzer> (Swapper*, unsigned short)>::operator()() (this=0x35287660) at /usr/include/c++/4.8.2/functional:1720
#33 0x00000000005292a2 in std::thread::_Impl<std::_Bind_simple<std::reference_wrapper<Analyzer> (Swapper*, unsigned short)> >::_M_run() (this=0x35287648) at /usr/include/c++/4.8.2/thread:115
#34 0x00007ffff528b070 in ?? () from /lib64/libstdc++.so.6
#35 0x00007ffff6b42e25 in start_thread () from /lib64/libpthread.so.0
#36 0x00007ffff49efbad in clone () from /lib64/libc.so.6
```

**Comment by Xiche** [comment]
This seems to have disappeared a while ago, pretty sure 15fd27f7daa747066de8010a9a4b58d12a9f69fa nailed it while fixing another issue.  Thanks for reporting!
